import * as core from "./core/protocol.js";
import {
  MightyClient,
  MightyWebDevice,
  DEFAULT_BASE_URLS,
  DEFAULT_ALGORITHMS_MODULE_URL,
  DEFAULT_ALGORITHMS_WASM_URL,
  MightyOccupancyGrid,
  OCCUPANCY_STATE,
  NativeLoopClosureWasm,
  NativeMapperWasm,
  createAlgorithmsWasmModule,
  decodeRawToRgb,
  decodeImageToRgb,
  decodeJpegToRaw,
  imageToRaw,
  RgbdSynchronizer,
  colorizeDepth,
  depthAtMeters,
  isUint16MetricDepth,
  rectifyImageToDepth,
  parseCalibrationYaml,
  FRC_TAG_SIZE_M, parseWpilibFieldLayout, serializeApriltagMapYaml,
  normalizeTagQuaternion, wpilibTagQuaternionToMighty, mightyTagQuaternionToWpilib,
} from "./sdk/index.js";

const { default: _coreDefault, ...coreNamed } = core;

const sdk = {
  MightyClient,
  MightyWebDevice,
  DEFAULT_BASE_URLS,
  DEFAULT_ALGORITHMS_MODULE_URL,
  DEFAULT_ALGORITHMS_WASM_URL,
  MightyOccupancyGrid,
  OCCUPANCY_STATE,
  NativeLoopClosureWasm,
  NativeMapperWasm,
  createAlgorithmsWasmModule,
  decodeRawToRgb,
  decodeImageToRgb,
  decodeJpegToRaw,
  imageToRaw,
  RgbdSynchronizer,
  colorizeDepth,
  depthAtMeters,
  isUint16MetricDepth,
  rectifyImageToDepth,
  parseCalibrationYaml,
  FRC_TAG_SIZE_M, parseWpilibFieldLayout, serializeApriltagMapYaml,
  normalizeTagQuaternion, wpilibTagQuaternionToMighty, mightyTagQuaternionToWpilib,
};

const api = {
  ...coreNamed,
  ...sdk,
  sdk,
  core: coreNamed,
};

export * from "./core/protocol.js";
export {
  MightyClient,
  MightyWebDevice,
  DEFAULT_BASE_URLS,
  DEFAULT_ALGORITHMS_MODULE_URL,
  DEFAULT_ALGORITHMS_WASM_URL,
  MightyOccupancyGrid,
  OCCUPANCY_STATE,
  NativeLoopClosureWasm,
  NativeMapperWasm,
  createAlgorithmsWasmModule,
  decodeRawToRgb,
  decodeImageToRgb,
  decodeJpegToRaw,
  imageToRaw,
  RgbdSynchronizer,
  colorizeDepth,
  depthAtMeters,
  isUint16MetricDepth,
  rectifyImageToDepth,
  parseCalibrationYaml,
  FRC_TAG_SIZE_M, parseWpilibFieldLayout, serializeApriltagMapYaml,
  normalizeTagQuaternion, wpilibTagQuaternionToMighty, mightyTagQuaternionToWpilib,
  sdk,
  coreNamed as core,
};
export default api;
